#!/bin/bash

# Run Clients:
./Klient.out -# 4 -r 1.5 12345 &
./Klient.out -# 3 -r .3 12345 &
./Klient.out -# 5 -r 1.5 127.0.0.1:12345 &
./Klient.out -#5 -r 1.5 localhost:12345 & 
./Klient.out -#3 -s2 LOCALHOST:12345 &
./Klient.out -#4 -s3 LoCaLHOST:12345 &
./Klient.out -#2 -r3.2 :12345 &
./Klient.out -#2 -r3.5 :12345 &
./Klient.out -#2 -r3.7 12345 
